/**
 * Generate self-hosted CJK subsets.
 *
 * Noto Serif HK and SC are ~9MB each across all Unicode ranges, and letting a
 * build tool self-host every subset produced 223 files and 14MB here. This site
 * uses roughly 150 distinct Chinese characters, all of them known ahead of time,
 * so it asks Google Fonts for a subset containing exactly those glyphs and
 * serves the result from our own origin. The files come out a few tens of KB.
 *
 * The character set is READ FROM THE SOURCE, not hand-maintained: add a word or
 * a label and re-run `npm run fonts`.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const OUT_DIR = join(ROOT, 'public', 'fonts');
const CSS_OUT = join(ROOT, 'app', 'fonts-cjk.css');

/** Files whose Chinese characters must be renderable. */
const SOURCES = [
  'components/entrance/lib/content.ts',
  'components/site/SiteShell.tsx',
  'app/programme/page.tsx'
];

const FAMILIES = [
  { family: 'Noto Serif HK', slug: 'noto-serif-hk', weights: [300, 400] },
  { family: 'Noto Serif SC', slug: 'noto-serif-sc', weights: [300, 400] }
];

// A modern Chrome UA, so Google serves woff2 rather than truetype.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) ' +
  'Chrome/131.0.0.0 Safari/537.36';

const CJK = /[　-〿㐀-䶿一-鿿豈-﫿＀-￯]/u;

async function collectCharacters() {
  const found = new Set();
  for (const relative of SOURCES) {
    const text = await readFile(join(ROOT, relative), 'utf8');
    for (const character of text) {
      if (CJK.test(character)) found.add(character);
    }
  }
  // Punctuation the copy relies on, in case a source ever drops it.
  for (const character of '，。？！、：；「」（）') found.add(character);
  return Array.from(found).sort().join('');
}

async function fetchSubset(family, weight, text) {
  const url =
    `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@${weight}` +
    `&text=${encodeURIComponent(text)}&display=swap`;
  const css = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!css.ok) throw new Error(`${family} ${weight}: CSS request failed (${css.status})`);
  const body = await css.text();

  const match = /src:\s*url\((https:\/\/[^)]+)\)\s*format\('([^']+)'\)/.exec(body);
  if (!match) throw new Error(`${family} ${weight}: no font URL in the returned CSS`);
  const [, fontUrl, format] = match;
  if (format !== 'woff2') {
    throw new Error(`${family} ${weight}: expected woff2, got ${format}`);
  }

  const font = await fetch(fontUrl, { headers: { 'User-Agent': UA } });
  if (!font.ok) throw new Error(`${family} ${weight}: font download failed (${font.status})`);
  return Buffer.from(await font.arrayBuffer());
}

const text = await collectCharacters();
console.log(`character set: ${text.length} distinct CJK characters`);
await mkdir(OUT_DIR, { recursive: true });

const faces = [];
for (const { family, slug, weights } of FAMILIES) {
  for (const weight of weights) {
    const buffer = await fetchSubset(family, weight, text);
    const file = `${slug}-${weight}.woff2`;
    await writeFile(join(OUT_DIR, file), buffer);
    console.log(`  ${file}  ${(buffer.length / 1024).toFixed(1)} KB`);
    faces.push(
      `@font-face {\n` +
        `  font-family: '${family}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${file}') format('woff2');\n` +
        `}`
    );
  }
}

await writeFile(
  CSS_OUT,
  `/* GENERATED by tools/make-fonts.mjs — do not edit. Run \`npm run fonts\`. */\n` +
    `/* Subsets containing only the ${text.length} Chinese characters this site uses. */\n\n` +
    faces.join('\n\n') +
    '\n',
  'utf8'
);
console.log(`wrote ${CSS_OUT}`);
